name: Builder


on:
  schedule:
  - cron: "59 * * * *"

  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: BUILDER
        run: |
          wget https://raw.githubusercontent.com/raj-extremegamerz/Godot_Arm64_Builder/main/setlinux.sh
          chmod +x setlinux.sh
          sh setlinux.sh

      - uses: actions/upload-artifact@v3
        with:
          name: Godot_Arm64
          path: ~/godot/bin
          if-no-files-found: warn
