# This is a basic workflow to help you get started with Actions

name: Builder

# Controls when the workflow will run
on:
schedule:
  - cron: "*/10 * * * *"
jobs:
    build:
     runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Run a one-line script
      #  run: 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/raj-extremegamerz/Godot_Arm64_Builder/main/setlinux.sh
          chmod +x setlinux.sh
          sh setlinux.sh
