name: Builder


on:
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build_Editor:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: BUILDER
        run: |
          wget https://raw.githubusercontent.com/raj-extremegamerz/Godot_Arm64_Builder/main/Build_Editor.sh
          chmod +x Build_Editor.sh
          sh Build_Editor.sh

      - uses: actions/upload-artifact@v3
        with:
          name: Godot_Editor_Arm64
          path: ~/godot/bin/godot*editor.arm64
          if-no-files-found: error

  build_Tools:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: BUILDER
        run: |
          wget https://raw.githubusercontent.com/raj-extremegamerz/Godot_Arm64_Builder/main/Build_Tools.sh
          chmod +x Build_Tools.sh
          sh Build_Tools.sh

      - uses: actions/upload-artifact@v3
        with:
          name: Godot_TOOLS_Arm64
          path: ~/godot/bin/*template_debug.arm64
          if-no-files-found: error

